# Nom du workflow
name: "Déploiement auto suite à un push"

# Déclencheuf
on:
  push:
    branches:
      -dev


# ------------------------------------------

jobs:
  creation-vm:
    name: "Création instance Ubuntu"
    runs-on: ubuntu-latest

    steps:
      - name : "Création du jeu de clés pour l'utilisateur deploy"
        # Récupération des secrets
        env: 
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}

        run: |
          # Fichier SSH
          mkdir
          
          # Connexion


          # Git push
